apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ql02do3xk-go 
  janus-idp.io/tekton: ql02do3xk-go
  backstage.io/kubernetes-id: ql02do3xk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ql02do3xk-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml